global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'knowthis'
    static_configs:
      - targets: ['knowthis:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']